In [1]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from sklearn.decomposition import PCA
from sklearn.neighbors import LocalOutlierFactor
import sys
from embedding import Graph2Vec
from sqlalchemy import create_engine
import pymysql
import pandas as pd
import os
import datetime
import time

In [2]:
db_connection_str = 'mysql+pymysql://root:caucse1234@caucse.club/virus'
db_connection = create_engine(db_connection_str)
df = pd.read_sql('SELECT test.city,weather.* FROM weather,test where weather.KID=test.KID and test.city="부산광역시" and weather.date >="20200101" AND weather.date <"20200330"', con=db_connection)
df1 = df.iloc[:,3:]

In [3]:
df1

qiwen  shidu  zhengqiya  ludianwendu  dangdiqiya  haimianqiya  \
0      -2.5   23.0        1.2        -20.8      1021.7       1030.7   
1      -2.9   22.0        1.1        -21.7      1021.6       1030.6   
2      -3.1   23.0        1.1        -21.3      1021.6       1030.6   
3      -2.8   24.0        1.2        -20.6      1021.1       1030.1   
4      -3.1   35.0        1.7        -16.4      1021.0       1030.0   
...     ...    ...        ...          ...         ...          ...   
2131   10.0   60.0        7.3          2.5      1012.4       1020.9   
2132    9.8   61.0        7.4          2.6      1012.4       1020.9   
2133    9.5   61.0        7.2          2.3      1012.9       1021.4   
2134    9.4   62.0        7.3          2.4      1012.7       1021.2   
2135    9.2   63.0        7.3          2.5      1012.7       1021.2   

      dimianqiya  
0           -1.4  
1           -1.6  
2           -1.9  
3           -2.0  
4           -2.1  
...          ...  
2131        10.3  
2132         9.5  
2133         9.0  
2134         8.7  
2135         8.7  

[2136 rows x 7 columns]

In [4]:
def processingforcorr(data):
        Corr = data.corr().values
        Corr = np.abs(Corr)
        Corr = pd.DataFrame(Corr)
        return Corr.fillna(0).values

def Graph(data):
    maxlag = 1
    test = 'ssr_chi2test'
    X = []
    new = processingforcorr(data.iloc[:24])
    X.append(new)
    i = 1
    while i<=data.shape[0]-25:
        new = processingforcorr(data.iloc[i:i+24])
        X.append(new)
        i=i+24
            
    return np.array(X)

def entropy(X):
        E = []
        for i in range(X.shape[0]):
            P = []
            for j in range(X.shape[1]):
                if i !=j:
                    e = -X[i][j]*np.log(X[i][j])
                    P.append(e)
            P = np.array(P)
            E.append(np.sum(P))
        return np.array(E)

def graphentropy(X):
        E = []
        for i in range(X.shape[0]):
            e = entropy(X[i])
            E.append(np.sum(e))
        return np.array(E)

def distance(x,y):
        distance = np.mean(np.power((x - y),2))
        return distance

def getMatrix(data,E):
        Matrix = []
        for i in range(E.shape[0]):
            dis = []
            for j in range(len(E)):
                dis.append(distance(E[i],E[j]))
            dis = np.array(dis)
            index = np.argsort(dis)[1]
            Matrix.append(data[index])
            
        return np.array(Matrix)

In [5]:
x = Graph(df1)
X = x.reshape(-1,49)
pca = PCA(n_components=4*4)
X= pca.fit_transform(X)
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        if X[i][j] == 0:
                X[i][j] = 1
X = np.abs(X.reshape(X.shape[0],4,4))

In [6]:
E = graphentropy(X)

MatrixX = getMatrix(X,E)

TrainXTensor = torch.from_numpy(X.reshape(X.shape[0], 16)).type(torch.FloatTensor)
TrainSTensor = torch.from_numpy(MatrixX.reshape(X.shape[0], 16)).type(torch.FloatTensor)
        
model = torch.load('Model.pth')
model.eval()
ed1, ed2, de1, de2 = model(TrainXTensor, TrainSTensor)
Embed = ed1.data.numpy()

df_Embed = pd.DataFrame(Embed)
df_Embed.columns = ['C0','C1','C2','C3','C4','C5','C6','C7','C8','C9']

In [7]:
a={"2020-01-01":Embed[0]}

In [8]:
a["2020-01-01"]

array([ 3.7961709e-03,  8.7568164e-04, -4.1726762e-03, -3.8819322e-03,
        5.1941647e-04, -1.4003091e-03, -4.1509424e-03, -7.5396383e-05,
        6.7933730e-04, -1.3466865e-03], dtype=float32)

In [9]:
s1 = "20200101"
a = time.strptime(s1,'%Y%m%d')
start=a[:3]
s2 = "20200330"
b= time.strptime(s2,'%Y%m%d')
end=b[:3]


In [10]:
starttime=datetime.date(start[0],start[1],start[2])
endtime=datetime.date(end[0],end[1],end[2])
a=(endtime-starttime).days
a

89

In [11]:
day=[]
for i in range(a+1):
    day1=starttime+datetime.timedelta(days=i)
    day.append(str(day1))


In [12]:
dic={}
for key in day:
    dic[key]=0
len(dic)

90

In [13]:
Embed[3]

array([ 3.5369911e-03,  9.0428605e-04, -3.6874739e-03, -3.4643672e-03,
       -1.2835953e-05, -1.4273049e-03, -3.9497651e-03,  1.4228420e-04,
        7.3403574e-04, -1.4214721e-03], dtype=float32)

In [14]:
for i in range(len(dic)-1):
    dic[day[i]]=Embed[i]
dic['2020-01-01']

array([ 3.7961709e-03,  8.7568164e-04, -4.1726762e-03, -3.8819322e-03,
        5.1941647e-04, -1.4003091e-03, -4.1509424e-03, -7.5396383e-05,
        6.7933730e-04, -1.3466865e-03], dtype=float32)

In [15]:
lof = LocalOutlierFactor(n_neighbors=10, contamination=0.2, algorithm='auto', n_jobs=-1, novelty=True)
lof.fit(Embed)
y_pred_outliers_LOF = lof.predict(Embed)